//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAllotmentHUB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProject
    {
        public EmployeeProject()
        {
            this.EmployeeStatus = new HashSet<EmployeeStatu>();
        }
    
        public int EmployeeProject_Id { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Roles_Id { get; set; }
        public int EmployeeStream_Id { get; set; }
        public int Project_Id { get; set; }
    
        public virtual EmployeeStream EmployeeStream { get; set; }
        public virtual Project Project { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<EmployeeStatu> EmployeeStatus { get; set; }
    }
}
