//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAllotmentHUB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeStreams = new HashSet<EmployeeStream>();
        }
    
        public int Employee_Id { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeId { get; set; }
        public long EmployeePhno { get; set; }
        public string EmployeeMailId { get; set; }
        public System.DateTime DOJ { get; set; }
        public string StatusInfo { get; set; }
    
        public virtual ICollection<EmployeeStream> EmployeeStreams { get; set; }
    }
}
