//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAllotmentHUB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeStream
    {
        public EmployeeStream()
        {
            this.EmployeeProjects = new HashSet<EmployeeProject>();
        }
    
        public int EmployeeStream_Id { get; set; }
        public int Employee_Id { get; set; }
        public int Stream_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<EmployeeProject> EmployeeProjects { get; set; }
        public virtual Stream Stream { get; set; }
    }
}
