//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAllotmentHUB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeStatu
    {
        public int EmployeeStatus_Id { get; set; }
        public string StatusType { get; set; }
        public int EmployeeProject_Id { get; set; }
    
        public virtual EmployeeProject EmployeeProject { get; set; }
    }
}
