//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAllotmentHUB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stream
    {
        public Stream()
        {
            this.EmployeeStreams = new HashSet<EmployeeStream>();
        }
    
        public int Stream_Id { get; set; }
        public string COEname { get; set; }
        public string COEmailId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string StreamName { get; set; }
    
        public virtual ICollection<EmployeeStream> EmployeeStreams { get; set; }
    }
}
